language: node_js
node_js:
  - "lts/*"
  - "node"

cache: bundler

install:
  - cd client/
  - npm install
  - cd ../server/
  - npm install
  - cd ..

script:
  - cd client/
  - npm run build
  - npm run test
  - cd ../server
  - npm run build
  - npm run test

notifications:
  email:
    on_success: never
    on_failure: never
