language: node_js
node_js:
  - "lts/*"
  - "node"
  - "10"

install:
  - ./scripts/install.sh

stages:
  - build
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: build
      script: ./scripts/build-client.sh
      script: ./scripts/build-server.sh
    - stage: test
      script: ./scripts/test-client.sh
      script: ./scripts/test-server.sh
    # - stage: deploy
    #   script: ./deploy

# script:
#   - cd client/
#   - npm run test && npm run build
#   - cd ../server/
#   - npm run test
#   - cd ..

notifications:
  email:
    on_success: never
    on_failure: never