language: node_js
node_js:
  - "lts/*"
  - "node"

install:
  - cd client/
  - npm install
  - cd ../server/
  - npm install
  - cd ..

script:
  - cd client/
  - npm run test && npm run build
  - cd ../server/
  - npm run test
  - cd ..