export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN = 'LOGIN';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOAD_EVENTS_SUCCESS = 'LOAD_EVENTS_SUCCESS';
export const LOAD_EVENT_SUCCESS = 'LOAD_EVENT_SUCCESS';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';

export const UPDATE_PLACE_SUCCESS = 'UPDATE_PLACE_SUCCESS';
export const CREATE_PLACE_SUCCESS = 'CREATE_PLACE_SUCCESS';
export const LOAD_PLACES_SUCCESS = 'LOAD_PLACES_SUCCESS';

export const SUCCESS_NOTIFICATION = 'SUCCESS_NOTIFICATION';
export const ERROR_NOTIFICATION = 'ERROR_NOTIFICATION';

export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';

export const LOAD_SPORTS_SUCCESS = 'LOAD_SPORTS_SUCCESS';
export const UPDATE_SPORT_SUCCESS = 'UPDATE_SPORT_SUCCESS';
export const CREATE_SPORT_SUCCESS = 'CREATE_SPORT_SUCCESS';
export const DELETE_SPORT_SUCCESS = 'DELETE_SPORT_SUCCESS';

export const GET_LOGGED_USER = 'GET_LOGGED_USER';

export const JOIN_REQUEST_SUCCESS = 'JOIN_REQUEST_SUCCESS';
export const RESPOND_TO_REQUEST_SUCCESS = 'RESPOND_TO_REQUEST_SUCCESS';

export const LEAVE_REVIEW_SUCCESS = 'LEAVE_REVIEW_SUCCESS';

export const TOGGLE_ADMIN_SUCCESS = 'TOGGLE_ADMIN_SUCCESS';

// Profile
export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS';

export const LOAD_MESSAGES_SUCCESS = 'LOAD_MESSAGES_SUCCESS';
